//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailingMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoReng
    {
        public int reng_num { get; set; }
        public int co_doc { get; set; }
        public string co_serv { get; set; }
        public string des_serv { get; set; }
        public int cantidad { get; set; }
        public string co_mone { get; set; }
        public decimal price_serv { get; set; }
        public decimal price_bsd { get; set; }
        public decimal price_usd { get; set; }
        public decimal price_eur { get; set; }
        public Nullable<decimal> price_liq { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string mone_liq { get; set; }
        public string tip_precio { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
