//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SailingMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioServicio
    {
        public int ID { get; set; }
        public string co_serv { get; set; }
        public string campo_valor { get; set; }
        public decimal desde { get; set; }
        public decimal hasta { get; set; }
        public decimal precio_min { get; set; }
        public decimal precio_base { get; set; }
        public decimal precio_max { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
